# Wrangler configuration for Astro Blog with D1
# For more details: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "blog"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"

# Enable observability and source maps
observability = { enabled = true }
upload_source_maps = true

# Static assets configuration
[assets]
directory = "./dist"
binding = "ASSETS"

# Local Development Environment (Default)
[vars]
ENVIRONMENT = "local"

# Local Development D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "blog-local"
database_id = "local"

# Remote Development Environment
[env.dev]
name = "blog"

# Remote Development D1 Database bindings
# Run: npx wrangler d1 create blog-dev
# Then replace "your-dev-database-id-here" with the actual database ID
[[env.dev.d1_databases]]
binding = "DB"
database_name = "blog-dev"
database_id = "your-dev-database-id-here"

[env.dev.vars]
ENVIRONMENT = "development"

# Production Environment
[env.production]
name = "blog"

# Production D1 Database bindings
# Run: npx wrangler d1 create blog-prod
# Then replace "your-prod-database-id-here" with the actual database ID
[[env.production.d1_databases]]
binding = "DB"
database_name = "blog-prod"
database_id = "your-prod-database-id-here"

[env.production.vars]
ENVIRONMENT = "production"

# KV storage for sessions (commented out, uncomment when needed)
# [[kv_namespaces]]
# binding = "SESSION"
# id = "session_kv_namespace_id_placeholder"

# Production KV storage (if needed)
# [[env.production.kv_namespaces]]
# binding = "SESSION"
# id = "production_session_kv_namespace_id"

# Note: Use `wrangler secret put ADMIN_PASSWORD` to set sensitive data
# For production: `wrangler secret put ADMIN_PASSWORD --env production`
